# Copyright 2021 The Khronos Group, Inc.
# SPDX-License-Identifier: Apache-2.0

# Github CI file for vulkan spec and header generation

name: CI

defaults:
  runs-on: ubuntu-latest
  container: khronosgroup/docker-images:asciidoctor-spec

# Controls when the action will run.
on:
  # Triggers the workflow on push or manual dispatch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#  license-check:
#    steps:
#      - uses

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Use Khronos container with asciidoctor toolchain preinstalled
    container: khronosgroup/docker-images:asciidoctor-spec

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Unfortunately, asciidoctor-pdf gets pathname-specific errors
      # building under the usual $GITHUB_WORKSPACE (/__w). As a workaround,
      # generate the outputs in /tmp.

      - name: Build spec targets
        run: |
          cd adoc
          make OUTDIR=/tmp/out QUIET= html pdf
      - name: Archive generated files
        uses: actions/upload-artifact@v2
        with:
          name: spec-outputs
          path: |
            /tmp/out
